### PR TITLE
Fix for WEP and proper auth_alg bitmask

### PR DESCRIPTION
**Pull request by jimklimov**
Document stuff vs android docs; add a simple self-test

### CODE REVIEW

**Comment by mnalis** [comment]
Thanks for the effort on improving this! Could you update just two minor things before I pull this:

- add yourself as one of the authors at the top of `.pl` script
- shorten TODO list at bottom of `README.md` with the fixes you added?

Thanks!

**Comment by jimklimov** [comment]
Updated, hopefully ok to go :)

**Comment by mnalis** [comment]
Thanks, look good!

Just final verification before I pull: 
You also release all your changes under Apache 2.0 license (as the original code does), correct?

**Comment by jimklimov** [comment]
Yes, licensing so is okay with me.
Jim Klimov

**Comment by mnalis** [comment]
Thanks again for your work, merged!

**Pull request merged**
